---
title: "Interactive Markdown Exercise 2"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(MASS)
```

# My first Interactive ggplot

Using `ggplot(mtcars, aes(wt, mpg))`, add interactive components to include:

1. Radio buttons to show or hide the dots & lm
1. Radio buttons to choose model ("lm", "loess", or "rlm", a _robust_ lm from the `MASS` package)
1. Slider input to choose the span (0.15 - 0.90) when using LOESS model

For extra practice:

- Option to show or hide the SE on the models
- Slide for the alpha in the dots


```{r echo = FALSE}


inputPanel(
  # XXXXXX,  # input 1
  # XXXXXX,  # input 2
  # XXXXXX   # input 2
)

renderPlot({
  
  # Define the base layer
  p <- ggplot(mtcars, aes(wt, mpg))
  
  # addPoints <- XXXXXX # add points geom
  
  # addModel <- XXXXXX # add stats model

  # Now define how to display:  
  # if (XXXXXX == XXXXXX) {
  #   XXXXXX
  # } else if (XXXXXX == XXXXXX) {
  #   XXXXXX
  # } else if (XXXXXX == XXXXXX) {
  #   XXXXXX
  # }

  })

```
